pipelines_configs:
- data_settings:
    data_handling:
      feature_remove_by_null_percentage: 0.3
      features_for_train: []
      features_handling:
        bmi:
          fillna: np.mean
          transformation:
          - np.square
        glu:
          fillna: np.mean
          transformation:
          - np.square
        hdl:
          fillna: np.mean
          transformation:
          - np.square
        tch:
          fillna: np.mean
          transformation:
          - np.square
      features_to_bin:
      - bins:
        - -0.05
        - 0.03
        name: tch
      - bins:
        - 0.07
        name: hdl
      features_to_remove:
      - age
      - sex
      - tc
      - ldl
      - age_sex
      - sex_age
      - age_hdl
      - hdl_age
      - sex_tc
      - tc_sex
      - sex_ldl
      - ldl_sex
      - bmi_hdl
      - hdl_bmi
      - map_hdl
      - hdl_map
      - tc_hdl
      - hdl_tc
      - hdl_tch
      - tch_hdl
      - hdl_ltg
      - ltg_hdl
      - hdl_glu
      - glu_hdl
      interactions: true
      set_features_index: []
    data_sources:
      local:
        file_paths:
        - data/diabetes.csv
  job_settings:
    asset_name: advanced_regression
    pipeline: train
  model_settings:
    auto_ml:
      estimators:
        linear:
          models:
          - Lasso
          - Ridge
        non_linear:
          hyper_params:
            RandomForest:
              max_depth:
              - 1
              - 3
              n_estimators:
              - 10
              - 50
          models:
          - RandomForest
          - ExtraTree
      feature_selection:
      - method: SelectKBest
        params:
          k: 7
          score_func: f_regression
      - method: RFE
        params:
          estimator: SVR(kernel='linear')
          n_features_to_select: 5
          step: 1
      - method: AllFeatures
    train_percent: 0.8
    variable_to_predict: target
