flow_config:
  data_settings:
    data_handling:
      agg_function_dataframe: np.sum
      agg_on_columns:
      - y_hat
    data_index:
    - index
    data_output_keys:
    - missing_values
    flow_return_data: predictions
    flow_return_features:
    - df
  job_settings:
    asset_name: flow_regression
    pipeline: forecast_flow
  model_settings:
    variable_to_predict: target
pipelines_configs:
- data_settings:
    data_sources:
      local:
        file_paths:
        - data/diabetes.csv
  flow_settings:
    input_from_predecessor: []
    return_value:
    - predictions
  job_settings:
    asset_name: advanced_regression
    data_id: latest
    model_id: latest
    pipeline: forecast
- data_settings:
    data_sources:
      local:
        file_paths:
        - data/diabetes.csv
  flow_settings:
    input_from_predecessor:
    - predictions
    return_value:
    - predictions
  job_settings:
    asset_name: advanced_regression
    data_id: latest
    model_id: latest
    pipeline: forecast
