pipelines_configs:
- job_settings:
    asset_name: classification
    data_id: latest
    pipeline: reuse_features_and_train
    reuse_features_id: latest
  model_settings:
    auto_ml:
      binary:
        fixed_params:
          ExtraTreeClassifier:
            class_weight: balanced
            max_depth: 10
            min_samples_leaf: 4
          Logistic:
            max_iter: 500
            solver: liblinear
        hyper_params:
          ExtraTreeClassifier:
            min_samples_split:
            - 2
            - 10
            n_estimators:
            - 10
            - 50
            - 200
          Logistic:
            C: list(np.linspace(0.01, 4, 15))
            class_weight:
            - balanced
            - null
            fit_intercept:
            - true
            penalty:
            - l1
            - l2
          XGBoostClassifier:
            learning_rate: list(np.linspace(0.001, 0.02, 3))
            max_depth:
            - 3
            - 7
            - 10
            min_child_weight:
            - 3
            - 10
            n_estimators:
            - 300
            - 500
            - 700
        models:
        - XGBoostClassifier
        - Logistic
        - ExtraTreeClassifier
      feature_selection:
      - method: SelectKBest
        params:
          k: 7
          score_func: chi2
    down_sample_method:
      flag: false
      n_samples: 100
      seed: 1500
    predict_proba_threshold:
    - 0.05
    - 0.5
    - 0.95
    train_percent: 0.8
    variable_to_predict: answer
