pipelines_configs:
- data_settings:
    data_handling:
      feature_remove_by_null_percentage: 0.3
      features_for_train: []
      features_to_remove:
      - sex
      set_features_index: []
    local_file_path: data/diabetes.csv
    variable_to_predict: target
  flow_settings:
    input_from_predecessor:
    - contributer_name
    return_value:
    - predictions
  job_settings:
    asset_name: basic_regression
    pipeline: train
  model_settings:
    train_percent: 0.8
    variable_to_predict: target
