pipelines_configs:
- data_settings:
    data_handling:
      auto_get_dummies: true
      bin_continuous_features: true
      dates_format: yyyyMMdd
      dates_transformation:
        columns: []
        extraction_date: '20180430'
      default_missing_value: 0
      feature_remove_by_null_percentage: 0.3
      features_for_filter: {}
      features_for_train: null
      features_handling:
        mean radius:
          fillna: mean
          transformation:
          - 'lambda a: F.pow(a, 2)'
          - F.sqrt
        radius error:
          fillna: 0
          transformation: []
      features_interactions: []
      features_to_bin:
      - bins:
        - 12.3
        - 15.3
        name: mean radius
      - bins:
        - 15
        - 23
        name: mean texture
      - bins:
        - 72
        - 109
        name: mean perimeter
      - bins:
        - 361
        - 886
        name: mean area
      - bins:
        - 0.074
        - 0.11
        name: mean smoothness
      - bins:
        - 0.047
        - 0.137
        - 0.228
        name: mean compactness
      - bins:
        - 0.023
        - 0.12
        name: mean concavity
      - bins:
        - 4
        name: mean concave points
      - bins:
        - quantile
        name: mean symmetry
      - bins:
        - 0.0518
        - 0.0541
        - 0.0742
        - 0.0827
        name: mean fractal dimension
      - bins:
        - 0.19
        - 0.56
        - 0.83
        name: radius error
      - bins:
        - 500
        - 1050
        name: worst area
      - bins:
        - 85
        - 120
        name: worst perimeter
      - bins:
        - 16.6
        - 42
        name: worst texture
      - bins:
        - 12.5
        - 18
        name: worst radius
      - bins:
        - 0.006
        - 0.0135
        name: fractal dimension error
      - bins:
        - 0.011
        - 0.082
        - 0.15
        name: concavity error
      - bins:
        - 1.3
        - 5
        name: perimeter error
      features_to_convert_to_dummies:
      - mean radius
      - mean texture
      - mean perimeter
      - mean area
      - mean smoothness
      - mean compactness
      - mean concavity
      - mean concave points
      - mean symmetry
      - mean fractal dimension
      - radius error
      - worst area
      - worst perimeter
      - worst texture
      - worst radius
      - fractal dimension error
      - concavity error
      - perimeter error
      features_to_remove:
      - texture error
      - area error
      - smoothness error
      - compactness error
      - concave points error
      - symmetry error
      - worst smoothness
      - worst compactness
      - worst concavity
      - worst concave points
      - worst symmetry
      - worst fractal dimension
      max_categories_num: 10
      set_features_index: null
      y_variable:
        categories_labels:
        - NEGATIVE
        - POSITIVE
        continuous_to_category_bins:
        - -1
        - 1
        - 2
        label_to_predict:
        - POSITIVE
        type: binary
    data_output_keys:
      images_files: []
      results:
      - missing_values
      - evaluator_features_mappings
    local_data_csvs:
    - name: breast_cancer
      path: data/breast_cancer.csv
    model_name: breast_cancer
    variable_to_predict: answer
  job_settings:
    asset_name: spark_classification
    data_id: latest
    model_id: latest
    pipeline: forecast
  model_settings:
    custom_tables: {}
    model_output_keys: {}
    output_columns_rename: {}
    y_label: POSITIVE
    y_name: answer
