pipelines_configs:
- data_settings:
    conf_extend_dataframe:
      exp: true
      interactions: 2
      log: true
    file_path: data/glass.csv
  job_settings:
    asset_name: crash_course
    pipeline: train
  model_settings:
    auto_ml:
      fixed_params:
        ExtraTreeClassifier:
          class_weight: balanced
          max_depth: 10
          min_samples_leaf: 4
      hyper_params:
        ExtraTreeClassifier:
          min_samples_split:
          - 2
          - 10
          n_estimators:
          - 10
          - 50
          - 200
        RandomForest:
          max_depth: range(1, 3)
          n_estimators:
          - 400
          - 700
          - 1000
      models:
      - RandomForest
      - ExtraTreeClassifier
    target: Type
    train_percent: 0.9
